### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/MSA#6]
- [ ] Handle synonyms
- [ ] Prune leaves for cognate sets
- [ ] Sum of WSOP across concepts
- [ ] Progressive alignment (Thompson)
- [ ] Sample branch lengths
